apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
spec:
  containers:
    - image: kodekloud/webapp-color
      name: webapp-green
      args: ["--color", "green"]




#!/bin/sh
if [[ -f /home/centos/vantagecircle/RUNNING_PID ]]
then
    echo "<<<<<<<<<<<<<<<<RUNNING PID exists......Moving to Deploy...>>>>>>>>>>>>>>>>>>>"
else
   echo "<<<<<<<<<<<<<RUNNING_PID does not exists creating a fake process and moving to deploy >>>>>>>>>>>>"
   bash -c 'exec -a sadhadxk sleep 1000000' &
   touch /home/centos/RUNNING_PID
   pgrep -f sadhadxk  > /home/centos/RUNNING_PID
   touch /home/centos/vantagecircle/RUNNING_PID
   tail -1 /home/centos/RUNNING_PID  > /home/centos/vantagecircle/RUNNING_PID
   rm /home/centos/RUNNING_PID
fi
