#apiVersion: v1
#kind: Secret
#metadata:
#  name: app-secret
#
#data:
#  DB_HOST: host
#  DB_USER: mysql
#  DB_PASSWD: asdasda
#
#
#
#
#
#
#
#
##echo -n 'root' | base64
##echo -n 'root' | base64 --decode

#apiVersion: v1
#kind: Pod
#metadata:
#  name: webapp-pod
#
#spec:
#  containers:
#    - name: webapp-pod
#      image: kodekloud/simple-webapp-mysql
#
#      envFrom:
#       - secretRef:
#           name: db-secret

#
#apiVersion: v1
#kind: Pod
#metadata:
#  name: yellow
#
#spec:
#  containers:
#    - name: lemon
#      image: busybox
#
#    - name: gold
#      image: redis

apiVersion: v1
kind: Pod
metadata:
  name: red

spec:
  initContainers:
    - name: busybox-container
      image: busybox
      command:
          sh
          -c
          sleep 20

