version: "3"
services:
    timeline:
        build: .
        links:
            - db
            - redis
            - memcached

        ports:
            - 9000:9000
        stdin_open: true
        volumes:
            - ./timelinefeed:/timelinefeed

    redis:  

        image: redis
        hostname: redis
        ports:
            - 6379:6379

    db: 

        image: mysql
        hostname: db
        environment:
            MYSQL_ROOT_PASSWORD: tdp_passwd
            MYSQL_DATABASE: thedealspoint
            MYSQL_USER: tdp_user
            MYSQL_PASSWORD: tdp_passwd
        ports:
            - 3306:3306    

    memcached:
    
        image: memcached
        hostname: memcached
        ports:
            - 11211:11211
        extra_hosts:
            - "vantagecircle.local:127.0.0.1"
            - "server-test:159.89.166.228"
        



