#apiVersion: v1
#kind: Pod
#
#metadata:
#  name: myapp-pod
#  labels:
#    app: myapp-pod
#    type: front-end
#spec:
#  containers:
#    - name: nginx-container
#      image: nginx



apiVersion: v1
kind: Pod

metadata:
  name: webapp-color
  labels:
    name: webapp-color

spec:
  containers:
    - name: webapp-container
      image: kodekloud/webapp-color
      env:
        - name: APP_COLOR
          value: green